Update password

diff --git a/libexec/functions/password b/libexec/functions/password
--- a/libexec/functions/password
+++ b/libexec/functions/password
@@ -1,12 +1,12 @@
-#!/data/data/com.termux/files/usr/bin/bash
+#!/usr/bin/env bash
 #
-source ${HOME}/.UMBRELLA/UMBRELLA/variables
-source ${UMBRELLA}/functions
-COMMANDS termux-toast termux-api
-COMMANDS openssl openssl-tool
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' does not exist!.\033[0m\n"; exit 1; }
 
-HELP() {
-	printf "${yellow}USAGE: ${green}password${yellow} [ ${red}-g${yellow} | ${red}-s${yellow} | ${red}-n${yellow} ] password for login in UMBRELLA SHELL.
+check_dependencies termux-toast
+check_dependencies openssl
+
+usage() {
+	printf "${yellow}USAGE:${green} password ${yellow}[ ${red}-g${yellow} | ${red}-s${yellow} | ${red}-n${yellow} ] password for login in UMBRELLA SHELL.
   For more help type ${green}UMBRELLA${yellow} [ ${red}-h${yellow} | ${red}--help${yellow} ] for helpper UMBRELLA CORPORATION.
 	
   OPTIONS:
@@ -14,30 +14,29 @@ HELP() {
   ${red}-s${yellow} ┆┄┄┄┄┄┄┆ ${red}--set${yellow}    ┆┅┅┅┅┅┅┆ Set password for login, enable or disable.
   ${red}-n${yellow} ┆┄┄┄┄┄┄┆ ${red}--new${yellow}  ┆┅┅┅┅┅┅┆ Create new password. ${default}\n\n";}
 
-[[ -z $1 ]] && { HELP; exit 1; }
+if [[ -z "$1" ]]; then usage ; exit 1 ;fi
 
-[[ -n $1 ]] && {
-	case "$1" in
-		-h|--help)
-			HELP;
-			exit 0;
-		  ;;
-		-g|--get)
-			trap ctrl_c 2;
-theme cyan
-			ctrl_c(){ pass Get; }
-			pass Get
-			;;
-		-s|--set)
-theme cyan
-			pass set
-			;;
-		-n|--new)
-			pass New
-			;;
-		*)
-			about
-			;;
-	esac
-}
+case $1 in
+  -h|--help)
+    usage
+    exit 0
+    ;;
+  -g|--get)
+    trap ctrl_c 2;
+    theme cyan
+    ctrl_c(){ pass Get; }
+    pass Get
+    ;;
+  -s|--set)
+    theme cyan
+    pass Set
+    ;;
+  -n|--new)
+    pass New
+    ;;
+  *)
+    usage ; info ; exit 1;
+    ;;
+esac
+
 
