Update functions

diff --git a/UMBRELLA/functions b/UMBRELLA/functions
--- a/UMBRELLA/functions
+++ b/UMBRELLA/functions
@@ -3,14 +3,34 @@
 source "${HOME}/.UMBRELLA/UMBRELLA/variables" || { echo -en "\033[31mError:\033[33m File 'variables' is required but not exist!.\033[0m\n" ; exit 1; }
 
 log() {
-  local argv="$1"
-  echo -e "${blue}$argv${default}"
+  local argv="$2"
+  case "$1" in
+    -a)
+      echo -e "$A ${blue}$argv${default}"
+      log_data "[+] $argv"
+      ;;
+    -d)
+      echo -e "$D ${blue}$argv${default}"
+      log_data "[✔] $argv"
+      ;;
+    *)
+      echo -e "${blue}$1${default}"
+      ;;
+  esac
 }
 export -f log
 
 error() {
   local argv="$1"
-  log "$E $argv"
+
+  if [[ "$argv" == "-l" ]]; then
+    log "$E ${orange}$2${default}"
+    log_data "[✖] Error: $2"
+    return 0
+  else
+    log "$E ${orange}$argv${default}"
+    return
+  fi
 }
 export -f error
 
@@ -24,9 +44,8 @@ export -f log_data
 check_file() {
   local files=("$@")
   for file in "${files[@]}"; do
-    log_data "Checking file $file"
     if [ ! -f "$file" ]; then
-      echo -en "\033[31m[✖] Error:\033[33mFile '$file' is required but not exist!."
+      error -l "File '$file' is required but not exist!."
       exit 1;
     fi
   done
@@ -53,9 +72,9 @@ theme() {
 export -f theme
 
 update_system() {
-  log "$A Update system ... "
-  if ! pkg update && upgrade -y &>>"$LOG_FILE"; then
-    error "The dependencies could not be updated!."
+  log -a "Update system ... "
+  if ! apt update && apt upgrade -y 2>&1; then
+    error -l "The dependencies could not be updated!."
   fi
 }
 export -f update_system
@@ -63,9 +82,8 @@ export -f update_system
 check_dependencies() {
   local argv=("$@")
   for dep in "${argv[@]}"; do
-    log_data "Checking $dep "
     if ! command -v "$dep" &>/dev/null; then
-      echo -en "${red}[✖] Error:${yellow} '$dep' is required but not installed. ${default}\n"
+      error -l "'$dep' is required but not installed."
       exit 1;
     fi
   done
@@ -76,15 +94,14 @@ install_dependencies() {
   local dependencies=("$@")
 
   for dep in "${dependencies[@]}"; do
-    log_data "Checking $dep "
     if command -v "$dep" &>/dev/null; then
-      log "$D $dep Already is installed!."
+      log -d "$dep Already is installed!."
     else
-      log "$A Installing dependencies $dep...  "
+      log -a "Installing dependencies $dep...  "
       if ! pkg install -y "$dep"; then
         error "Could not be installed '$dep'."
       fi
-      log "$D $dep Installed Successfully!."
+      log -d "$dep Installed Successfully!."
     fi
   done
 }
@@ -101,7 +118,7 @@ helpper() {
   ❉ ${green}adduser${yellow}     ┄┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-n  ${yellow}| ${red}--new${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Add a username.
                             ┆${red}-r ${yellow}| ${red}--remove${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Remove your username.
   ❉ ${green}check-data${yellow}   ┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Show the processes and data made of changes or customization of UMBRELLA CORPORATION.
-                            ┆ ${red}-h${yellow}--| ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Menu help check-data.
+                            ┆ ${red}-h${yellow}--| ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Menu help check-logs.
   ❉ ${green}password${yellow}     ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-n  ${yellow}| ${red}--new  ${yellow}┆┅┅┅┅┅┄┄┄┄┇ Add/get a password to log in to login UMBRELLA.
                             ┆  ${red}passwd set${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Set mode enable/password in login.
   ❉ ${green}theme${yellow}        ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-c ${yellow}| ${red}--color${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Set a banner color that providedUMBRELLA CORPORATION. Available colors: cyan, red and dark.
@@ -112,7 +129,7 @@ helpper() {
 
   \n✲ THIS COMMANDS THERE FUNCTIONS TO UMBRELLA CORPORATION ✲
                  ✲ Commands ✲
-   COMMANDS             ∵           DESCRIPTION$D
+      COMMANDS                ∵                DESCRIPTION
   ❉ ${green}archivos${yellow}      ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ File management of your Android.
   ❉ ${green}apkinf${yellow}        ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Provides information on phone applications.
   ❉ ${green}df${yellow}            ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that shows information about the available and total space in a file system.
@@ -125,8 +142,8 @@ helpper() {
   ❉ ${green}tree${yellow}          ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ File Map/Map Display.
   ❉ ${green}tldr${yellow}          ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Command Manual/Command Usage.
   ❉ ${green}traductor${yellow}     ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Init a command line traductor.
-  ❉ ${green}X11_distro${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Utility that lets you run your Linux distribution in a desktop environment.
-  ❉ ${green}X11_native${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that allows you to run a Linux environment on an Android device.
+  ❉ ${green}x11-distro${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Utility that lets you run your Linux distribution in a desktop environment.
+  ❉ ${green}x11-native${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that allows you to run a Linux environment on an Android device.
   ┇┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇${default}\n\n"
 }
 export -f helpper
@@ -138,23 +155,26 @@ pass () {
     Set)
       check_file "${files[@]}"
       login=$(grep "pass" ${libexec}/UMBRELLA.login | tail -n 1)
-      select opt in Password Disable Exit; do
+      select opt in Password Disable Exit Fingerprint; do
         case "$opt" in
           Exit) exit 0 ;;
           Password)
             opt="Get"
             sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
-            log_data "Enable password"
-            log "$D Enable password sucessfully!"
+            log "$D ${blue}Enable password sucessfully!"
             break ;;
           Disable)
             opt=""
             sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
-            log_data "Disable password"
-            log "$D Disable password sucessfully!"
+            log "$D ${blue}Disable password sucessfully!"
+            break ;;
+          Fingerprint)
+            opt="fingerprint"
+            sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
+            log "$D ${blue}Settings fingerprint successfully"
             break ;;
           *)
-            echo -e "${red}Error:${yellow} No valid option!. Try again.${default}"
+            error "No valid option!. Try again."
             ;;
         esac
       done
@@ -174,26 +194,29 @@ pass () {
         local encrypted=$(echo $pass|openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 -salt -pass pass:dynamic_key)
         sed -i "s|$fpasswd|PASSWORD : $encrypted|" ${UMBRELLA}/passwd
 
-        log "Password saved successfully!.\e[0m\n"
+        log "$D ${blue}Password saved successfully!.\n"
       else
         error "Password do noy match."
         pass New
       fi
-      log_data "Add new password"
+      log -d "Add new password"
       ;;
     Get)
       check_file "${files[@]}"
       local passwd=$(grep "PASSWORD" ${UMBRELLA}/passwd | tail -n 1)
       if [[ -z "$passwd" ]]; then
-        error "No password found in the file."
-        return 1
+        echo "PASSWORD" >> ${UMBRELLA}/passwd
       fi
-
-      local encrypted_pass=$(echo "$passwd" | awk '{print $NF}')
+      local passwd=$(grep "PASSWORD" ${UMBRELLA}/passwd | tail -n 1)
+      local encrypted_pass=$(echo "$passwd" | awk '{print $3}')
       if [[ -z "$encrypted_pass" ]]; then
-        error "Encrypted password is empty."
-        return 1
+        error "Encrypted password is empty, defining default password!."
+        log "$D ${blue}Password saved successfully\n"
+        local pass_default=$(echo "UMBRELLA"|openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 -salt -pass pass:dynamic_key)
+        sed -i "s|$passwd|PASSWORD : $pass_default|" ${UMBRELLA}/passwd
       fi
+      local passwd=$(grep "PASSWORD" ${UMBRELLA}/passwd | tail -n 1)
+      local encrypted_pass=$(echo "$passwd" | awk '{print $NF}')
       decrypted_pass=$(echo "$encrypted_pass" | openssl enc -aes-256-cbc -md sha512 -a -d -pbkdf2 -iter 100000 -salt -pass pass:dynamic_key 2>/dev/null)
       if [[ $? -ne 0 ]]; then
         error "Failed to decrypt the password. Check the encryption format or key."
@@ -211,20 +234,42 @@ pass () {
         attempt=$((attempt + 1))
         if [[ $attempt -ge $max_attempts ]]; then
           error "Maximum attempts reached. Exiting."
-          log_data "Failed to input correct password after $max_attempts attempts."
+          error "Failed to input correct password after $max_attempts attempts."
           sleep 2
           pkill com.termux
         fi
         error "Retype the password"
-        log_data "Error to get password (Attempt: $attempt)"
+        error "Error to get password (Attempt: $attempt)"
         pass=""
         while read -sp "Password: " pass && [[ -z "$pass" ]]; do
           error "Input password!.\n"
           continue
         done
       done
-      log "$D Password sucessfully!\nWELCOME TO  U M B R E L L A  C O R P O R A T I O N"
-      log_data "Input password successfully"
+      log "$D ${blue}Password sucessfully!\nWELCOME TO  U M B R E L L A  C O R P O R A T I O N"
+      ;;
+    fingerprint)
+      local get=$(termux-fingerprint | jq -r '.auth_result' | awk 'NF{print $NF}' FS=RESULT_)
+
+      if [[ $? -ne 0 ]]; then
+        error "When detecting the fingerprint sensor!."
+        pass Get
+        return 0
+      else
+        until [[ "$get" = "SUCCESS" ]]; do
+          if [[ "$get" == "FAILURE" ]] || [[ -z "$get" ]]; then
+            error "When detecting fingerprint."
+            pass Get
+            return 0
+          fi
+          if [[ "$get" == "UNKNOWN" ]]; then
+            error -l "You have no defined fingerprint, go to your settings and define your fingerprint!."
+            pass Get
+            return 0
+          fi
+        done
+      fi
+      log "$D ${blue}Password sucessfully!\nWELCOME TO  U M B R E L L A  C O R P O R A T I O N"
       ;;
   esac
 }
