Update functions

diff --git a/UMBRELLA/functions b/UMBRELLA/functions
--- a/UMBRELLA/functions
+++ b/UMBRELLA/functions
@@ -1,37 +1,58 @@
-#!/usr/bin/bash
-#This file contain all UMBRELLA functions
-source ${HOME}/.UMBRELLA/UMBRELLA/variables
-theme() {
-  [[ $1 = dark ]] && {
-  Dark="/data/data/com.termux/files/home/.UMBRELLA/UMBRELLA/BANNER/dark"
-  bash $Dark;
-  sleep 0.5; }
-  [[ $1 = red ]] && {
-  Red="/data/data/com.termux/files/home/.UMBRELLA/UMBRELLA/BANNER/red"
-  bash $Red;
-  sleep 0.5; }
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/variables" || { echo -en "\033[31mError:\033[33m File 'variables' is required but not exist!.\033[0m\n" ; exit 1; }
 
-  [[ $1 = cyan ]] && {
-  Cyan="/data/data/com.termux/files/home/.UMBRELLA/UMBRELLA/BANNER/cyan"
-  bash $Cyan
-  sleep 0.5; }
+LOGFILE="${HOME}/.UMBRELLA/UMBRELLA/UMBRELLA.dat"
+
+log_data() {
+  if [ ! -f "$LOGFILE" ]; then touch "$LOGFILE"; fi
+  local message="$1"
+  echo "[ $(date '+%Y-%m-%d %H:%M:%S') ] : $message" >> "$LOGFILE"
+}
+export -f log_data
+
+check_file() {
+  local files=("$@")
+  for file in "${files[@]}"; do
+    log_data "Checking file $file"
+    if [ ! -f "$file" ]; then
+      echo -en "\033[31m[✖] Error:\033[33mFile '$file' is required but not exist!."
+      exit 1;
+    fi
+  done
+}
+export -f check_file
+
+info() {
+  echo -en "${yellow}For more help type ${green}UMBRELLA${yellow} [${red} -h${yellow} |${red} --help${yellow} ] for helpper UMBRELLA CORPORATION.${default}\n"
+}
+export -f info
+
+theme() {
+  local files=("${BANNER}/dark" "${BANNER}/cyan" "${BANNER}/red")
+  local argv="$1"
+  check_file "$files"
+  declare -A color=(
+  ["dark"]="${BANNER}/dark"
+  ["red"]="${BANNER}/red"
+  ["cyan"]="${BANNER}/cyan"
+)
+  bash "${color[$argv]}"
+  sleep 0.5;
 }
 export -f theme
 
-ctrl_c() {
-  exit 0;
+check_dependencies() {
+  local argv=("$@")
+  for dep in "${argv[@]}"; do
+    log_data "Checking $dep "
+    if ! command -v "$dep" &>/dev/null; then
+      echo -en "${red}[✖] Error:${yellow} '$dep' is required but not installed. ${default}\n"
+      exit 1;
+    fi
+  done
 }
-export -f ctrl_c
-about() {
-	printf "${bold}${red}(⋯☣) ${yellow}Invalid argument, type ${green}UMBRELLA ${red}--help${yellow} for helpper.${default}\n"
-}
-export -f about
-
-COMMANDS() {
-
-  command -v $1 >/dev/null || { printf "${red}${bold}(⋯☣) ${yellow}UMBRELLA CORPORACION need $1. -->${underline}Run apt install $2${default}\n";exit;}
-}
-export -f COMMANDS
+export -f check_dependencies
 
 helpper() {
   printf "${yellow}☣ U M B R E L L A ☣ C O R P O R A T I O N ☣ ${version} (c) by LAWRENCE •‣ It is a custom configuration tool that makes it simple to perform basic tasks. At Umbrella Corporation we believe that nothing is impossible. If you can imagine it, you can create it!. The following is the help menu that provides you with the available tools that you can use to make using our tool easier.\nSyntax: COMMANDS [-args-] [-descriptions-]\n 
@@ -43,7 +64,8 @@ helpper() {
   ❉ ${green}UMBRELLA${yellow}     ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-h  ${yellow}| ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Help from UMBRELLA CORPORATION.
   ❉ ${green}adduser${yellow}     ┄┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-n  ${yellow}| ${red}--new${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Add a username.
                             ┆${red}-r ${yellow}| ${red}--remove${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Remove your username.
-  ❉ ${green}day ${yellow}| ${green}night ${yellow}| ${green}sepia${yellow}  ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ To quickly switch the color mode background.
+  ❉ ${green}check-data${yellow}   ┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Show the processes and data made of changes or customization of UMBRELLA CORPORATION.
+                            ┆ ${red}-h${yellow}--| ${red}--help${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Menu help check-data.
   ❉ ${green}password${yellow}     ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-n  ${yellow}| ${red}--new  ${yellow}┆┅┅┅┅┅┄┄┄┄┇ Add/get a password to log in to login UMBRELLA.
                             ┆  ${red}passwd set${yellow}  ┆┅┅┅┅┅┄┄┄┄┇ Set mode enable/password in login.
   ❉ ${green}theme${yellow}        ┄┄┄┄┄┅┅┅┅┅┅┆ ${red}-c ${yellow}| ${red}--color${yellow} ┆┅┅┅┅┅┄┄┄┄┇ Set a banner color that providedUMBRELLA CORPORATION. Available colors: cyan, red and dark.
@@ -68,58 +90,67 @@ helpper() {
   ❉ ${green}tldr${yellow}          ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Command Manual/Command Usage.
   ❉ ${green}traductor${yellow}     ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Init a command line traductor.
   ❉ ${green}X11_distro${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ Utility that lets you run your Linux distribution in a desktop environment.
-  ❉ ${green}X11_distro${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that allows you to run a Linux environment on an Android device.
+  ❉ ${green}X11_native${yellow}    ┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇ It is a tool that allows you to run a Linux environment on an Android device.
   ┇┄┄┄┄┄┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┄┄┄┄┇${default}\n\n"
 }
 export -f helpper
 
 pass () {
-  [[ $1 = set  ]] && {
+  local login_file="${libexec}/UMBRELLA.login"
+  local argv="$1"
+  case "$argv" in
+    Set)
       login=$(grep "pass" ${libexec}/UMBRELLA.login|tail -n 1)
-      select opt in Password Disable Exit
-      do
-        [[ $opt = Exit ]] && { exit 0; }
-        [[ $opt = Password ]] && { opt="Get"; }
-        sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
-        break
+      check_file "$login_file"
+      select opt in Password Disable Exit; do
+        case "$opt" in
+          Exit) exit 0 ;;
+          Password)
+            opt="Get"
+            sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
+            log_data "Enable password"
+            break ;;
+          Disable)
+            opt=""
+            sed -i "s|$login|pass $opt|" $libexec/UMBRELLA.login
+            log_data "Disable password" ;;
+          *)
+            echo -e "${red}Error:${yellow} No valid option!. Try again.${default}"
+            ;;
+        esac
       done
-    }
-    [[ $1 = New ]] && {
-
-      while read -sp "New password: " pass && printf "\n" && [[ -z $pass ]]
-      do
+      ;;
+    New)
+      while read -sp "New password: " pass && printf "\n" && [[ -z $pass ]]; do
         continue
       done
       while read -sp "Retype new password: " pass2 && printf "\n" && [[ -z $pass2 ]]
       do
         continue
       done
-      [[ $pass = $pass2 ]] && {
+      if [[ $pass = $pass2 ]]; then
         echo $pass|openssl enc -aes-256-cbc -md sha512 -a -pbkdf2 -iter 100000 \
-        -salt -pass pass:Secret@123# > $HOME/.UMBRELLA/UMBRELLA/.lawrence;
-              echo -en "\e[34mPassword to start operations in the system, saved!.\e[0m\n";
-            } || { echo -en "\e[35mERROR:\e[0m Password do noy match.\n";pass New;
-          }
-        }
-  [[ $1 = Get ]] && {
-      while read -sp "Password: " pass && [[ -z $pass ]]
+          -salt -pass pass:Secret@123# > $HOME/.UMBRELLA/UMBRELLA/.passwd;
 
-      do
+        echo -en "\e[34mPassword to start operations in the system, saved!.\e[0m\n"
+      else
+        echo -en "\e[35mERROR:\e[0m Password do noy match.\n"
+        pass New
+      fi
+      log_data "Add new password"
+      ;;
+    Get)
+      while read -sp "Password: " pass && [[ -z $pass ]]; do
         continue
-      done;
-      until [[ $pass = $(cat $HOME/.UMBRELLA/UMBRELLA/.lawrence|openssl enc -aes-256-cbc -md sha512 -a -d -pbkdf2 -iter 100000  -salt -pass pass:Secret@123#) ]] && printf "\n"
-      do
-        echo -en "\e[35mERROR:\e[0m Retype the  password\n"
-        #termux-toast -b red Wrong password
+      done
+      until [[ $pass = $(cat $HOME/.UMBRELLA/UMBRELLA/.passwd|openssl enc -aes-256-cbc -md sha512 -a -d -pbkdf2 -iter 100000  salt -pass pass:Secret@123#) ]] && printf "\n"; do
+        echo -en "\e[35mERROR:\e[0m Retype the password\n"
+        log_data "Error to get password"
         pass Get
       done
-      #termux-toast -b green Welcome Back $user;
-    }
-
-  [[ $1 = Disable ]] && {
-      echo "Access without pass" >>$log
-        #termux-toast -b green Welcome Back $user;
-      }
-    }
+      log_data "Input password sucessfully"
+      ;;
+  esac
+}
 export -f pass
 
