Update all list tools

diff --git a/UMBRELLA/Tools/apktool b/UMBRELLA/Tools/apktool
--- a/UMBRELLA/Tools/apktool
+++ b/UMBRELLA/Tools/apktool
@@ -1,17 +1,31 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/apktool ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for apktool...\e[0m\n"
-    yes|pkg update && yes|pkg upgrade &>/dev/null;
-    yes|pkg install apksigner curl;
-    curl -s https://raw.githubusercontent.com/rendiix/termux-apktool/main/install.sh | bash
-    yes|pkg update && yes|pkg upgrade &>/dev/null;
-    yes|pkg install apktool
-    printf "\e[1;38;5;253mDone!
-    
-    Please Execute:
-    apktool <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
+main() {
+  local bin=("apksigner" "curl")
+
+  if [ ! -x $PREFIX/bin/apktool ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "$A Installing dependencies for apktool ... "
+    if curl -s https://raw.githubusercontent.com/rendiix/termux-apktool/main/install.sh | bash; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+
+    if ! pkg install apktool -y; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "apktool <argv>"
+else
+    log "$D Already Installed!"
+fi
+}
+
+main
diff --git a/UMBRELLA/Tools/aquatone b/UMBRELLA/Tools/aquatone
--- a/UMBRELLA/Tools/aquatone
+++ b/UMBRELLA/Tools/aquatone
@@ -1,20 +1,30 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/aquatone ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for aquatone...\e[0m\n"
-    yes|pkg update && pkg upgrade &>/dev/null;
-    yes|pkg install ruby
-    gem install aquatone
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("ruby")
+  if [ ! -x $PREFIX/bin/aquatone ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "$A Installing dependencies for aquatone ... "
+    if ! gem install aquatone; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/aquatone
     cat <<- Confg > $PREFIX/bin/aquatone
 #!/usr/bin/bash
 aquatone-discover "\$@"
 Confg
     chmod 711 $PREFIX/bin/aquatone
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "aquatone <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    aquatone <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/arjun b/UMBRELLA/Tools/arjun
--- a/UMBRELLA/Tools/arjun
+++ b/UMBRELLA/Tools/arjun
@@ -1,15 +1,24 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/arjun ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for arjun...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python3
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install arjun
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    arjun <argv>\e[0m\n";
+main() {
+  local bin=("python3")
+  if [ ! -x $PREFIX/bin/arjun ]; then
+    install_dependencies "${bin[@]}"
+    log "$A Installing dependencies for arjun ... "
+    update_system
+    if ! python3 -m pip install arjun; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "arjun <argv>"
 else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
+  log "$D Already Installed!"
 fi
+}
+
+main
diff --git a/UMBRELLA/Tools/beef-xss b/UMBRELLA/Tools/beef-xss
--- a/UMBRELLA/Tools/beef-xss
+++ b/UMBRELLA/Tools/beef-xss
@@ -1,58 +1,59 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/beef-xss ]; then
-	echo -en "\e[1;4;38;5;253mInstalling dependencies for beef-xss...\e[0m\n"
-	yes|pkg update && pkg upgrade &>/dev/null;
-	yes|pkg install nodejs
-	yes|pkg install wget
-	UMBRELLA install metasploit
-	mkdir -p $PREFIX/etc/apt/sources.list.d
-	wget https://raw.githubusercontent.com/ivam3/termux-packages/gh-pages/ivam3-termux-packages.list -O $PREFIX/etc/apt/sources.list.d/ivam3-termux-packages.list
-	yes|apt update && apt upgrade &>/dev/null;
-	apt install beef
-	rm -rf $HOME/.local/share/beef
-  rm $PREFIX/bin/beef
-	rm -rf $PREFIX/etc/apt/sources.list.d
-	yes|apt update && apt upgrade &>/dev/null;
-	git clone https://github.com/beefproject/beef $PREFIX/opt/beef
-	cd $PREFIX/opt/beef
-	bundle install
-	rm config.yaml
-	rm extensions/social_engineering/mass_mailer/mass_mailer.rb
-	touch $PREFIX/bin/beef-xss
-	cat <<- Confg >$PREFIX/bin/beef-xss
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("nodejs" "wget" "ruby")
+
+  if [ ! -x $PREFIX/bin/beef-xss ]; then
+    install_dependencies "${bin[@]}"
+    log "$A Installing dependencies for beef-xss ... "
+    bash "${UMBRELLA}/Tools/metasploit"
+    git clone https://github.com/beefproject/beef $PREFIX/opt/beef
+    bundle "$PREFIX/opt/beef/install"
+    rm "$PREFIX/opt/beef/config.yaml"
+    rm "$PREFIX/opt/beef/extensions/social_engineering/mass_mailer/mass_mailer.rb"
+    touch $PREFIX/bin/beef-xss
+    cat <<- Confg >$PREFIX/bin/beef-xss
 #!/bin/bash
 beef="/data/data/com.termux/files/usr/opt/beef"
 cd \${beef}
 exec ruby "\${beef}/beef" "\$@"
 Confg
-	chmod 711 $PREFIX/bin/beef-xss
-	wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/beef-xss.zip -O $PREFIX/etc/beef-xss.zip
+    chmod 711 $PREFIX/bin/beef-xss
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/beef-xss.zip -O $PREFIX/etc/beef-xss.zip; then
+      if unzip "$PREFIX/etc/beef-xss.zip"; then
+        mv "$PREFIX/etc/beef-xss/GeoIP" $PREFIX/opt/beef
+        mv "$PREFIX/etc/beef-xss/mass_mailer.rb" "$PREFIX/opt/beef/extensions/social_engineering/mass_mailer"
+        mv "$PREFIX/etc/beef-xss/config.yaml" $PREFIX/opt/beef
+        mv "$PREFIX/etc/beef-xss/metasploit.rb" $PREFIX/opt/beef
+        rm -rf "$PREFIX/etc/beef-xss"
+        rm "$PREFIX/etc/beef-xss.zip"
+      else
+        error "It could not be installed the package!."
+      exit 1
+    fi
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    beefUser="UMBRELLA"
+    beefPass="UMBRELLA"
+    log "Username BEEf: "
+    read -r User
+    log "Password BEEf: "
+    read -r Pass
+    sed -i "s!${beefUser}!${User}!g" $PREFIX/opt/beef/config.yaml
+    sed -i "s!${beefPass}!${Pass}!g" $PREFIX/opt/beef/config.yaml
+    sed -i "s!${beefUser}!${User}!g" $PREFIX/opt/beef/metasploit.rb
+    sed -i "s!${beefPass}!${Pass}!g" $PREFIX/opt/beef/metasploit.rb
 
-	cd $PREFIX/etc/
-	unzip beef-xss.zip
-	cd beef-xss
-	mv GeoIP $PREFIX/opt/beef
-	mv mass_mailer.rb $PREFIX/opt/beef/extensions/social_engineering/mass_mailer
-	mv config.yaml $PREFIX/opt/beef
-	mv metasploit.rb $PREFIX/opt/beef
-	cd ..
-	rm -rf beef-xss
-	rm -rf beef-xss.zip
-	beefUser="UMBRELLA"
-	beefPass="UMBRELLA"
-	echo -en "\e[1;4;38;5;253mUsername BEEf: \n"
-	read -r User
-	echo -en "\e[1;4;38;5;253mPassword BEEf: \n"
-	read -r Pass
-	sed -i "s!${beefUser}!${User}!g" $PREFIX/opt/beef/config.yaml
-	sed -i "s!${beefPass}!${Pass}!g" $PREFIX/opt/beef/config.yaml
-	sed -i "s!${beefUser}!${User}!g" $PREFIX/opt/beef/metasploit.rb
-	sed -i "s!${beefPass}!${Pass}!g" $PREFIX/opt/beef/metasploit.rb
-	printf "\e[1;38;5;253mDone!
-	Please Execute:
-
-	beef-xss <argv>\e[0m\n";
-else
-	echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "beef-xss <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
+main
diff --git a/UMBRELLA/Tools/crunch b/UMBRELLA/Tools/crunch
--- a/UMBRELLA/Tools/crunch
+++ b/UMBRELLA/Tools/crunch
@@ -1,13 +1,21 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/crunch ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for crunch...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install crunch
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    crunch <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main() {
+  if [ ! -x $PREFIX/bin/crunch ]; then
+    log "Installing dependencies for crunch ... "
+    if ! pkg install crunch -y; then
+      error "It could not be installed packages!"
+      exit 1;
+    fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "crunch <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
+
+main
diff --git a/UMBRELLA/Tools/cupp b/UMBRELLA/Tools/cupp
--- a/UMBRELLA/Tools/cupp
+++ b/UMBRELLA/Tools/cupp
@@ -1,10 +1,16 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/cupp ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for cupp...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033
+[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }        
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/cupp ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for cupp ... "
+
+    update_system
+
     git clone https://github.com/Mebus/cupp $PREFIX/opt/cupp
     touch $PREFIX/bin/cupp
     cat <<- Confg > $PREFIX/bin/cupp
@@ -14,10 +20,13 @@ cd \${cupp}
 exec python3 "\${cupp}/cupp.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/cupp
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "cupp <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    cupp <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/dirb b/UMBRELLA/Tools/dirb
--- a/UMBRELLA/Tools/dirb
+++ b/UMBRELLA/Tools/dirb
@@ -1,13 +1,17 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/dirb ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for dirb...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install dirb
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    dirb <argv>\e[0m\n"
+if [ ! -x $PREFIX/bin/dirb ]; then
+  log"Installing dependencies for dirb ... "
+  if ! pkg install dirb -y; then
+    error "It could not be installed the package!."
+    exit 1
+  fi
+  log "$D Done!"
+  log "Please Execute:"
+  echo
+  log "dirb <argv>"
 else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
+  log "$D Already Installed!"
 fi
diff --git a/UMBRELLA/Tools/ecuador-id b/UMBRELLA/Tools/ecuador-id
--- a/UMBRELLA/Tools/ecuador-id
+++ b/UMBRELLA/Tools/ecuador-id
@@ -1,19 +1,26 @@
-#!/usr/bin/bash
-#
-if [ ! -x ${bin}/ecuador-id ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for ecuador-id...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    yes|pkg install wget
-    python3 -m pip install --upgrade pip &>/dev/null;
-    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/Ecuador-ID.zip -O $PREFIX/etc/Ecuador-ID.zip
-    cd $PREFIX/etc
-    unzip Ecuador-ID.zip
-    mv Ecuador-ID $PREFIX/opt
-    rm -rf Ecuador-ID.zip
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python" "wget")
+
+  if [ ! -x ${bin}/ecuador-id ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for ecuador-id ... "
+    update_system
+
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/Ecuador-ID.zip -O $PREFIX/etc/Ecuador-ID.zip; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    unzip "$PREFIX/etc/Ecuador-ID.zip"
+    mv $PREFIX/etc/Ecuador-ID $PREFIX/opt
+    rm $PREFIX/etc/Ecuador-ID.zip
     cd $PREFIX/opt/Ecuador-ID
     python3 -m pip install tabulate
     touch $PREFIX/bin/ecuador-id
+
     cat <<- Confg > $PREFIX/bin/ecuador-id
 #!/bin/bash
 EcuadorID="/data/data/com.termux/files/usr/opt/Ecuador-ID"
@@ -21,11 +28,13 @@ cd \${EcuadorID}
 exec python3 "\${EcuadorID}/Ecuador-ID.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/ecuador-id
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "ecuador-id <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    ecuador-id\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
-
+main
diff --git a/UMBRELLA/Tools/email2pn b/UMBRELLA/Tools/email2pn
--- a/UMBRELLA/Tools/email2pn
+++ b/UMBRELLA/Tools/email2pn
@@ -1,13 +1,22 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/email2pn ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for email2pn...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/email2pn ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for email2pn ... "
+
+    update_system
     git clone https://github.com/martinvigo/email2phonenumber $PREFIX/opt/email2phonenumber
     cd $PREFIX/opt/email2phonenumber
-    python3 -m pip install -r requirements.txt
+    if ! python3 -m pip install -r requirements.txt;then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+
     touch $PREFIX/bin/email2pn
     cat <<- Confg $PREFIX/bin/email2pn
 #!/bin/bash
@@ -16,10 +25,13 @@ cd \${email2pn}
 exec python3 "\${email2pn}/email2phonenumber.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/email2pn
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "email2pn <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    email2pn <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/evilurl b/UMBRELLA/Tools/evilurl
--- a/UMBRELLA/Tools/evilurl
+++ b/UMBRELLA/Tools/evilurl
@@ -1,11 +1,20 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/evilurl ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for evilurl...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install python-nmap python-whois
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033
+[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/evilurl ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for evilurl ... "
+
+    update_system
+    if ! python3 -m pip install python-nmap python-whois; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/UndeadSec/EvilURL $PREFIX/opt/EvilURL
     touch $PREFIX/bin/evilurl
     cat <<- Confg > $PREFIX/bin/evilurl
@@ -15,10 +24,13 @@ cd \${evilurl}
 exec python3 "\${evilurl}/evilurl.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/evilurl
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "hydra <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    evilurl <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/exiftool b/UMBRELLA/Tools/exiftool
--- a/UMBRELLA/Tools/exiftool
+++ b/UMBRELLA/Tools/exiftool
@@ -1,13 +1,19 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/exiftool ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for exiftool...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install exiftool
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    exiftool <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+
+if [ ! -x $PREFIX/bin/exiftool ]; then
+    log "Installing dependencies for exiftool ... "
+    if ! pkg install exiftool -y; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    update_system
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "exiftool <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/fbuserid b/UMBRELLA/Tools/fbuserid
--- a/UMBRELLA/Tools/fbuserid
+++ b/UMBRELLA/Tools/fbuserid
@@ -1,8 +1,15 @@
-#!/bin/bash
-if [ ! -x $PREFIX/bin/fbuserid ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for fbuserid...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install curl
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "curl")
+
+  if [ ! -x $PREFIX/bin/fbuserid ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for fbuserid ... "
+
+    update_system
     git clone https://github.com/Darkmux/fbuserid $PREFIX/opt/fbuserid
     cd $PREFIX/opt/fbuserid
     chmod 711 *.sh
@@ -14,10 +21,13 @@ cd \${fbuserid}
 exec bash "\${fbuserid}/fbuserid.sh" "\$@"
 Confg
     chmod 711 $PREFIX/bin/fbuserid
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "fbuserid <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    fbuserid <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/ghost b/UMBRELLA/Tools/ghost
--- a/UMBRELLA/Tools/ghost
+++ b/UMBRELLA/Tools/ghost
@@ -1,17 +1,26 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/ghost ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for ghost...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python3 android-tools git
-    yes|pkg install python-cryptography
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install git+https://github.com/EntySec/Ghost
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    ghost <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main() {
+  local bin=("git" "python3" "android-tools" "python-cryptography")
 
+  if [ ! -x $PREFIX/bin/ghost ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for ghost ... "
+
+    update_system
+    if ! python3 -m pip install git+https://github.com/EntySec/Ghost; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "ghost <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
+
+main
diff --git a/UMBRELLA/Tools/gobuster b/UMBRELLA/Tools/gobuster
--- a/UMBRELLA/Tools/gobuster
+++ b/UMBRELLA/Tools/gobuster
@@ -1,18 +1,27 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/gobuster ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for gobuster...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install golang
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "golang")
+
+  if [ ! -x $PREFIX/bin/gobuster ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for gobuster ... "
+
+    update_system
     git clone https://github.com/OJ/gobuster $PREFIX/opt/gobuster
     cd $PREFIX/opt/gobuster
     go get && go build
     ln -s $PREFIX/opt/gobuster/gobuster $PREFIX/bin/gobuster
     chmod 711 $PREFIX/bin/gobuster
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "gobuster <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    gobuster <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/gophish b/UMBRELLA/Tools/gophish
--- a/UMBRELLA/Tools/gophish
+++ b/UMBRELLA/Tools/gophish
@@ -1,13 +1,17 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/gophish ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies gophish...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install golang
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+main() {
+  local bin=("git" "golang")
+
+  if [ ! -x $PREFIX/bin/gophish ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for gophish ... "
+    update_system
+
     git clone https://github.com/gophish/gophish $PREFIX/opt/gophish
-    cd $PREFIX/opt/gophish
-    rm config.json
-    touch $PREFIX/opt/gophish/config.json
+    rm "$PREFIX/opt/gophish/config.json"
+    touch "$PREFIX/opt/gophish/config.json"
     cat <<- Confg > $PREFIX/opt/gophish/config.json
 {
   "admin_server": {
@@ -42,10 +46,13 @@ cd \${gophish}
 ./gophish "\$@"
 confg
     chmod 711 $PREFIX/bin/gophish
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "gophish <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    gophish <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/hash-buster b/UMBRELLA/Tools/hash-buster
--- a/UMBRELLA/Tools/hash-buster
+++ b/UMBRELLA/Tools/hash-buster
@@ -1,17 +1,20 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/buster ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for hash-buster...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/buster ]; then
+    log "Installing dependencies for hash-buster ..."
+    update_system
     git clone https://github.com/s0md3v/Hash-Buster $PREFIX/opt/Hash-Buster
     ln -s $PREFIX/opt/Hash-Buster/hash.py $PREFIX/bin/buster
-    chmod 711 $PREFIX/bin/buster
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    buster <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "buster <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
diff --git a/UMBRELLA/Tools/hash-id b/UMBRELLA/Tools/hash-id
--- a/UMBRELLA/Tools/hash-id
+++ b/UMBRELLA/Tools/hash-id
@@ -1,10 +1,14 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/hash-id ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for hash-id...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/hash-id ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for hash-id ... "
+    update_system
     git clone https://github.com/blackploit/hash-identifier $PREFIX/opt/hash-identifier
     touch $PREFIX/bin/hash-id
     cat <<- Confg > $PREFIX/bin/hash-id
@@ -14,10 +18,13 @@ cd \${hashid}
 exec python3 "\${hashid}/hash-id.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/hash-id
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "hash-id <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    hash-id <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/hashcrypt b/UMBRELLA/Tools/hashcrypt
--- a/UMBRELLA/Tools/hashcrypt
+++ b/UMBRELLA/Tools/hashcrypt
@@ -1,12 +1,20 @@
-#!/usr/bin/bash
-if [ ! -x $PREFIX/bin/hashcrypt ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for hashcrypt...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/hashcrypt ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for hashcrypt ... "
+    update_system
     git clone https://github.com/Darkmux/hashcrypt $PREFIX/opt/hashcrypt
-    cd $PREFIX/opt/hashcrypt
-    python3 -m pip install -r requirements.txt
+    if ! python3 -m pip install -r "$PREFIX/opt/hashcrypt/requirements.txt"; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+
     touch $PREFIX/bin/hashcrypt
     cat <<- Confg > $PREFIX/bin/hashcrypt
 #!/bin/bash
@@ -15,10 +23,13 @@ cd \${hashcrypt}
 exec python3 "\${hashcrypt}/hashcrypt-v2.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/hashcrypt
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "hydra <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    hashcrypt <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/holehe b/UMBRELLA/Tools/holehe
--- a/UMBRELLA/Tools/holehe
+++ b/UMBRELLA/Tools/holehe
@@ -1,14 +1,20 @@
-#!/usr/bin/bash
-if [ ! -x $PREFIX/bin/holehe ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for holehe...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python3
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install holehe
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    holehe <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+  if [ ! -x $PREFIX/bin/holehe ]; then
+    log "Installing dependencies for holehe ... "
+    install_dependencies python3
+    update_system
+    if ! python3 -m pip install holehe; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "holehe <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+
diff --git a/UMBRELLA/Tools/hydra b/UMBRELLA/Tools/hydra
--- a/UMBRELLA/Tools/hydra
+++ b/UMBRELLA/Tools/hydra
@@ -1,19 +1,27 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/hydra ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for hydra...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python clang
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("x11-repo" "git" "python3" "clang" "make" "openssl" "openssl-tool" "wget" "coreutils" "gtk2" "gtk3")
+
+  if [ ! -x $PREFIX/bin/hydra ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for hydra ... "
+    update_system
+
     git clone https://github.com/vanhauser-thc/thc-hydra $PREFIX/opt/thc-hydra
     cd $PREFIX/opt/thc-hydra
     ./configure --prefix=$PREFIX
     make
     make install
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "hydra <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    hydra <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/infoga b/UMBRELLA/Tools/infoga
--- a/UMBRELLA/Tools/infoga
+++ b/UMBRELLA/Tools/infoga
@@ -1,14 +1,19 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/infoga ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for infoga...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+  if [ ! -x $PREFIX/bin/infoga ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for infoga ... "
+    update_system
     git clone https://github.com/m4ll0k/Infoga $PREFIX/opt/Infoga
-    cd $PREFIX/opt/Infoga
-    python3 -m pip install -r requirements.txt
-    python3 setup.py install
+    if ! python3 -m pip install -r "$PREFIX/opt/Infoga/requirements.txt";then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    python3 $PREFIX/opt/Infoga/setup.py install
     touch $PREFIX/bin/infoga
     cat <<- Confg > $PREFIX/bin/infoga
 #!/bin/bash
@@ -17,10 +22,13 @@ cd \${infoga}
 exec python3 "\${infoga}/infoga.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/infoga
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "infoga <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    infoga <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/iphunter b/UMBRELLA/Tools/iphunter
--- a/UMBRELLA/Tools/iphunter
+++ b/UMBRELLA/Tools/iphunter
@@ -1,18 +1,27 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/iphunter ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for iphunter...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    yes|pkg install wget
-    python3 -m pip install --upgrade pip &>/dev/null;
-    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/iphunter.zip -O $PREFIX/etc/iphunter.zip
-    cd $PREFIX/etc/
-    unzip iphunter.zip
-    mv iphunter $PREFIX/opt/
-    rm -rf iphunter.zip
-    cd $PREFIX/opt/iphunter
-    python3 -m pip install -r requirements.txt &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("python3" "wget" "unzip")
+
+  if [ ! -x $PREFIX/bin/iphunter ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for iphunter ... "
+    update_system
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/iphunter.zip -O $PREFIX/etc/iphunter.zip; then
+      cd $PREFIX/etc/
+      unzip "$PREFIX/etc/iphunter.zip"
+      mv "$PREFIX/etc/iphunter" $PREFIX/opt/
+      rm "$PREFIX/etc/iphunter.zip"
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install -r "$PREFIX/opt/iphunter/requirements.txt"; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/iphunter
     cat <<- Confg > $PREFIX/bin/iphunter
 #!/bin/bash
@@ -21,10 +30,13 @@ cd \${iphunter}
 exec python3 "\${iphunter}/iphunter.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/iphunter
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "iphunter <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    iphunter\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/john b/UMBRELLA/Tools/john
--- a/UMBRELLA/Tools/john
+++ b/UMBRELLA/Tools/john
@@ -1,23 +1,28 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/john ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for jhon...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python clang
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3" "make")
+  if [ ! -x $PREFIX/bin/john ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for jhon ..."
+    update_system
     git clone https://github.com/openwall/john $PREFIX/opt/john
-    cd $PREFIX/opt/john/src
-    ./configure --prefix=$PREFIX
+    bash $PREFIX/opt/john/src/configure --prefix=$PREFIX
     make -s clean && make -sj4
     ln -s $PREFIX/opt/john/run $PREFIX/share/john
     ln -s $PREFIX/opt/john/run/john $PREFIX/bin/john
     ln -s $PREFIX/opt/john/run/zip2john $PREFIX/bin/zip2john
     ln -s $PREFIX/opt/john/run/rar2john $PREFIX/bin/rar2john
     ln -s $PREFIX/opt/john/run/ssh2john.py $PREFIX/bin/ssh2john
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
 
-    jhon <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "jhon <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
+main
diff --git a/UMBRELLA/Tools/magmaosint b/UMBRELLA/Tools/magmaosint
--- a/UMBRELLA/Tools/magmaosint
+++ b/UMBRELLA/Tools/magmaosint
@@ -1,22 +1,42 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3" "wget" "unzip")
+
 if [ ! -x $PREFIX/bin/magmaosint ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for magmaosint...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    yes|pkg install wget
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install fuzzywuzzy
-    python3 -m pip install requests
-    python3 -m pip install google
-    python3 -m pip install colorama
-    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/MagmaOsint.zip -O $PREFIX/etc/MagmaOsint.zip
-    cd $PREFIX/etc
-    unzip MagmaOsint.zip
-    mv MagmaOsint $PREFIX/opt/
-    rm -rf MagmaOsint.zip
-    cd $PREFIX/opt/MagmaOsint
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    log "Installing dependencies for magmaosint ... "
+    update_system
+    if ! python3 -m pip install fuzzywuzzy; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install requests; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install google; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install colorama; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/MagmaOsint.zip -O $PREFIX/etc/MagmaOsint.zip; then
+    unzip "$PREFIX/etc/MagmaOsint.zip"
+    mv "$PREFIX/etc/MagmaOsint" $PREFIX/opt
+    rm "$PREFIX/etc/MagmaOsint.zip"
+  else
+    error "It could not be installed the package!."
+      exit 1
+    fi
+    if python3 -m pip install -r "$PREFIX/opt/MagmaOsint/requirements.txt" &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+
     touch $PREFIX/bin/magmaosint
     cat <<- Confg > $PREFIX/bin/magmaosint
 #!/bin/bash
@@ -25,10 +45,13 @@ cd \${magmaosint}
 exec python3 "\${magmaosint}/osint.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/magmaosint
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "magmaosint <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    magmaosint\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/metagoofil b/UMBRELLA/Tools/metagoofil
--- a/UMBRELLA/Tools/metagoofil
+++ b/UMBRELLA/Tools/metagoofil
@@ -1,19 +1,28 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/metagoofil ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for metagoofil...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/metagoofil ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for metagoofil ... "
+    update_system
     git clone https://github.com/opsdisk/metagoofil $PREFIX/opt/metagoofil
-    cd $PREFIX/opt/metagoofil
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if !python3 -m pip install -r "$PREFIX/opt/metagoofil/requirements.txt" &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     ln -s $PREFIX/opt/metagoofil/metagoofil.py $PREFIX/bin/metagoofil
     chmod 711 $PREFIX/bin/metagoofil
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "metagoofil <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    metagoofil <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/metasploit b/UMBRELLA/Tools/metasploit
--- a/UMBRELLA/Tools/metasploit
+++ b/UMBRELLA/Tools/metasploit
@@ -1,39 +1,41 @@
-#!/usr/bin/bash
-#
-if [ ! -x ${bin}/msfconsole ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for metasploit-framework...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg uninstall ruby
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    if [ -d $HOME/metasploit-framework ]; then
-        rm -rf $HOME/metasploit-framework
+main() {
+  local bin=("git" "curl" "wget")
+  if [ ! -x ${bin}/msfconsole ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for metasploit-framework ... "
+    pkg uninstall ruby -y &>/dev/null;
+
+    if [ -d $HOME/metasploit-framework ]; then rm -rf $HOME/metasploit-framework; fi
+    if [ -d $PREFIX/opt/metasploit-framework ]; then rm -rf $PREFIX/opt/metasploit-framework; fi
+    if [ -x $PREFIX/bin/msfconsole ]; then rm $PREFIX/bin/msfconsole; fi
+    if [ -x $PREFIX/bin/msfvenom ]; then rm $PREFIX/bin/msfvenom; fi
+
+    if ! wget https://github.com/gushmazuko/metasploit_in_termux/raw/master/metasploit.sh -O ~/metasploit.sh; then
+      error "It could not be installed the package!."
+    else
+      chmod 777 ~/metasploit.sh
+      bash ~/metasploit.sh
+      rm metasploit.sh
     fi
-    if [ -d $PREFIX/opt/metasploit-framework ]; then
-        rm -rf $PREFIX/opt/metasploit-framework
+    if [ -f "$HOME/.UMBRELLA/Share/code.rb" ]; then
+      rm $PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
+      cp "$HOME/.UMBRELLA/Share/code.rb" "$PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry"
+    else
+      wget "raw.githubusercontent.com/Lawrence10Coroy/.UMBRELLA/refs/heads/master/Share/code.rb" -O "$PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb"
     fi
-    if [ -x $PREFIX/bin/msfconsole ]; then
-        rm $PREFIX/bin/msfconsole
-    fi
-    if [ -x $PREFIX/bin/msfvenom ]; then
-        rm $PREFIX/bin/msfvenom
-    fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "msfconsole <argv>"
+    log "----- or -----"
+    log "msfvenom <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    yes|pkg install curl
-    yes|pkg install wget
-    wget https://github.com/gushmazuko/metasploit_in_termux/raw/master/metasploit.sh -O ~/metasploit.sh
-    chmod 777 ~/metasploit.sh
-    bash ~/metasploit.sh
-    rm -rf metasploit.sh
-    rm $PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
-    cp $HOME/.UMBRELLA/Share/code.rb $PREFIX/usr/lib/ruby/gems/3.2.0/gems/pry-0.13.1/lib/pry/code.rb
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    msfconsole <argv>
-
-    ----- or -----
-
-    msfvenom <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/mosint b/UMBRELLA/Tools/mosint
--- a/UMBRELLA/Tools/mosint
+++ b/UMBRELLA/Tools/mosint
@@ -1,18 +1,25 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/mosint ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for mosint...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install golang
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "golang")
+
+  if [ ! -x $PREFIX/bin/mosint ]; then
+    log "Installing dependencies for mosint ... "
+    install_dependencies "${bin[@]}"
     git clone https://github.com/alpkeskin/mosint $PREFIX/opt/mosint
     cd $PREFIX/opt/mosint
     go get && go build
-    ln -s $PREFIX/opt/mosint/mosint $PREFIX/bin/mosint
+    cd && ln -s $PREFIX/opt/mosint/mosint $PREFIX/bin/mosint
     chmod 777 $PREFIX/bin/mosint
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "mosint <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    mosint <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/ncshare b/UMBRELLA/Tools/ncshare
--- a/UMBRELLA/Tools/ncshare
+++ b/UMBRELLA/Tools/ncshare
@@ -1,12 +1,15 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/ncshare ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for ncshare...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install nmap netcat-openbsd
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "nmap" "netcat-openbsd")
+
+  if [ ! -x $PREFIX/bin/ncshare ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for ncshare ... "
     git clone https://github.com/whitehacks00/ncshare $PREFIX/opt/ncshare
-    cd $PREFIX/opt/ncshare
-    chmod 711 *.sh
+    chmod 711 "$PREFIX/opt/ncshare/*.sh"
     touch $PREFIX/bin/ncshare
     cat <<- Confg > $PREFIX/bin/ncshare
 #!/bin/bash
@@ -15,10 +18,13 @@ cd \${NCShare}
 exec bash "\${NCShare}/ncshare.sh" "\$@"
 Confg
     chmod 711 $PREFIX/bin/ncshare
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "ncshare <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    ncshare\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/netcat b/UMBRELLA/Tools/netcat
--- a/UMBRELLA/Tools/netcat
+++ b/UMBRELLA/Tools/netcat
@@ -1,17 +1,18 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033
+[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
 if [ ! -x $PREFIX/bin/netcat ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for netcat...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install nmap netcat-openbsd
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    ncat <argv>
-
-    ------ or ------
-    
-    netcat <argv>\e[0m\n";
+  bin=("nmap" "netcat-openbsd")
+  log "Installing dependencies for netcat ... "
+  install_dependencies "${bin[@]}"
+  log "$D Done!"
+  log "Please Execute:"
+  echo
+  log "ncat <argv>"
+  log "------ or ------"
+  log "netcat <argv>"
 else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
+  log "$D Already Installed!"
 fi
diff --git a/UMBRELLA/Tools/nexfil b/UMBRELLA/Tools/nexfil
--- a/UMBRELLA/Tools/nexfil
+++ b/UMBRELLA/Tools/nexfil
@@ -1,15 +1,27 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/nexfil ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for nexfil...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install tldextract
-    python3 -m pip install aiohttp
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3")
+
+  if [ ! -x $PREFIX/bin/nexfil ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for nexfil ... "
+    update_system
+    if ! python3 -m pip install tldextract; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install aiohttp; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/thewhiteh4t/nexfil $PREFIX/opt/nexfil
-    cd $PREFIX/opt/nexfil
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r "$PREFIX/opt/nexfil/requirements.txt" &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/nexfil
     cat <<- Confg > $PREFIX/bin/nexfil
 #!/bin/bash
@@ -18,10 +30,13 @@ cd \${nexfil}
 exec python3 "\${nexfil}/nexfil.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/nexfil
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "nexfil <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    nexfil <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/nikto b/UMBRELLA/Tools/nikto
--- a/UMBRELLA/Tools/nikto
+++ b/UMBRELLA/Tools/nikto
@@ -1,18 +1,24 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/nikto ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for nikto...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install perl
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "perl")
+
+  if [ ! -x $PREFIX/bin/nikto ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for nikto ... "
     git clone https://github.com/sullo/nikto $PREFIX/opt/nikto
-    cd $PREFIX/opt/nikto/program
-    chmod 711 nikto.pl
+    chmod 711 $PREFIX/opt/nikto/program/nikto.pl
     ln -s $PREFIX/opt/nikto/program/nikto.pl $PREFIX/bin/nikto
     chmod 711 $PREFIX/bin/nikto
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "nikto <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    nikto <argv>\e[0m\n";
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/nmap b/UMBRELLA/Tools/nmap
--- a/UMBRELLA/Tools/nmap
+++ b/UMBRELLA/Tools/nmap
@@ -1,17 +1,24 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/nmap ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for nmap...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install nmap
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "nmap")
+
+  if [ ! -x $PREFIX/bin/nmap ]; then
+    log "Installing dependencies for nmap ... "
+    install_dependencies "${bin[@]}"
     git clone https://github.com/scipag/vulscan $PREFIX/opt/scipag_vulscan
     ln -s $PREFIX/opt/scipag_vulscan $PREFIX/share/nmap/scripts/vulscan
     git clone https://github.com/vulnersCom/nmap-vulners $PREFIX/opt/nmap-vulners
     ln -s $PREFIX/opt/nmap-vulners $PREFIX/share/nmap/scripts/nmap-vulners
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "nmap <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    nmap <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/whatweb b/UMBRELLA/Tools/whatweb
--- a/UMBRELLA/Tools/whatweb
+++ b/UMBRELLA/Tools/whatweb
@@ -1,9 +1,14 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/whatweb ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for whatweb...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install ruby
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("ruby")
+
+  if [ ! -x $PREFIX/bin/whatweb ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "$A Installing dependencies for whatweb ... "
     git clone https://github.com/urbanadventurer/WhatWeb $PREFIX/opt/WhatWeb
     cd $PREFIX/opt/WhatWeb
     bundle install
@@ -16,10 +21,13 @@ cd \${whatweb}
 exec ruby "\${whatweb}/whatweb" "\$@"
 Confg
     chmod 711 $PREFIX/bin/whatweb
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    whatweb <argv>\e[0m\n"
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "whatweb <argv>"
 else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
+    log "$D Already Installed!"
 fi
+}
+
+main
