Update tools

diff --git a/UMBRELLA/Tools/gobuster b/UMBRELLA/Tools/gobuster
--- a/UMBRELLA/Tools/gobuster
+++ b/UMBRELLA/Tools/gobuster
@@ -1,20 +1,27 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash -x
 #Useful functions for customization of the Umbrella
 source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
 main() {
-  local bin=("git" "golang")
+
+  local bin=("tar" "wget" "gzip")
 
   if [ ! -x $PREFIX/bin/gobuster ]; then
     install_dependencies "${bin[@]}"
     log "Installing dependencies for gobuster ... "
 
     update_system
-    git clone https://github.com/OJ/gobuster $PREFIX/opt/gobuster
-    cd $PREFIX/opt/gobuster
-    go get && go build
-    ln -s $PREFIX/opt/gobuster/gobuster $PREFIX/bin/gobuster
-    chmod 711 $PREFIX/bin/gobuster
+    if wget https://github.com/OJ/gobuster/releases/download/v3.6.0/gobuster_Linux_arm64.tar.gz; then
+      gzip --decompress -c gobuster_Linux_arm64.tar.gz > gobuster_Linux_arm64
+    fi
+      if command tar -xf gobuster_Linux_arm64; then
+      mv gobuster "${PREFIX}/bin"
+      rm gobuster_Linux_arm64
+      rm gobuster_Linux_arm64.tar.gz
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
     log "$D Done!"
     log "Please Execute:"
     echo
diff --git a/UMBRELLA/Tools/phone-dox b/UMBRELLA/Tools/phone-dox
--- a/UMBRELLA/Tools/phone-dox
+++ b/UMBRELLA/Tools/phone-dox
@@ -1,18 +1,26 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/phone-dox ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for phone-dox...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    yes|pkg install wget
-    python3 -m pip install --upgrade pip &>/dev/null;
-    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/Phone-dox.zip -O $PREFIX/tmp/Phone-dox.zip
-    cd $PREFIX/tmp
-    unzip Phone-dox.zip
-    mv Phone-dox $PREFIX/opt
-    rm -rf Phone-dox.zip
-    cd $PREFIX/opt/Phone-dox
-    python3 -m pip install -r requirements.txt &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("wget" "unzip" "python")
+
+  if [ ! -x $PREFIX/bin/phone-dox ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for phone-dox ... "
+    update_system
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/Phone-dox.zip -O $PREFIX/tmp/Phone-dox.zip; then
+      unzip $PREFIX/tmp/Phone-dox.zip
+      mv $PREFIX/tmp/Phone-dox $PREFIX/opt
+      rm $PREFIX/tmp/Phone-dox.zip
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install -r $PREFIX/opt/Phone-dox/requirements.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/phone-dox
     cat <<- Confg > $PREFIX/bin/phone-dox
 #!/bin/bash
@@ -21,10 +29,13 @@ cd \${PhoneDox}
 exec python3 "\${PhoneDox}/phone.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/phone-dox
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "phone-dox <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    phone-dox <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/phoneinfoga b/UMBRELLA/Tools/phoneinfoga
--- a/UMBRELLA/Tools/phoneinfoga
+++ b/UMBRELLA/Tools/phoneinfoga
@@ -1,14 +1,23 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/phoneinfoga ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for phoneinfoga...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python")
+
+  if [ ! -x $PREFIX/bin/phoneinfoga ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for phoneinfoga ... "
+    update_system
     git clone https://github.com/Darkmux/PhoneInfoga $PREFIX/opt/PhoneInfoga
-    cd $PREFIX/opt/PhoneInfoga
-    python3 -m pip install -r requirements.txt &>/dev/null;
-    python3 -m pip install config
+    if ! python3 -m pip install -r $PREFIX/opt/PhoneInfoga/requirements.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install $PREFIX/opt/PhoneInfoga/config; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/phoneinfoga
     cat <<- Confg > $PREFIX/bin/phoneinfoga
 #!/bin/bash
@@ -17,10 +26,13 @@ cd \${phoneinfoga}
 exec python3 "\${phoneinfoga}/phoneinfoga.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/phoneinfoga
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "phoneinfoga <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    phoneinfoga <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+  main
diff --git a/UMBRELLA/Tools/phonesploit b/UMBRELLA/Tools/phonesploit
--- a/UMBRELLA/Tools/phonesploit
+++ b/UMBRELLA/Tools/phonesploit
@@ -1,12 +1,20 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/phonesploit ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for phonesploit-pro...\e[0m\n"
-    yes|pkg update && yes|pkg upgrade
-    yes|pkg install python3 android-tools git
-    yes|pkg install python-cryptography
-    python3 -m pip install --upgrade pip &>/dev/null;
-    UMBRELLA install metasploit
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python3" "android-tools" "python-cryptography")
+
+  if [ ! -x $PREFIX/bin/phonesploit ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for phonesploit-pro ... "
+    update_system
+    if [ -f "${UMBRELLA}/Tools/metasploit" ]; then
+      bash "${UMBRELLA}/Tools/metasploit"
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/AzeemIdrisi/PhoneSploit-Pro $PREFIX/opt/PhoneSploit-Pro
     touch $PREFIX/bin/phonesploit
     cat <<- Confg > $PREFIX/bin/phonesploit
@@ -16,10 +24,13 @@ cd \${phonesploit}
 exec python3 "\${phonesploit}/phonesploitpro.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/phonesploit
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "phonesploit <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    phonesploit <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/photon b/UMBRELLA/Tools/photon
--- a/UMBRELLA/Tools/photon
+++ b/UMBRELLA/Tools/photon
@@ -1,13 +1,18 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+local bin=("git" "python3")
+
 if [ ! -x $PREFIX/bin/photon ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for photon...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+    log "Installing dependencies for photon ... "
+    install_dependencies "${bin[@]}"
+    update_system
     git clone https://github.com/s0md3v/Photon $PREFIX/opt/Photon
     cd $PREFIX/opt/Photon
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r $PREFIX/opt/Photon/requirements.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/photon
     cat <<- Confg > $PREFIX/bin/photon
 #!/bin/bash
@@ -16,10 +21,10 @@ cd \${photon}
 exec python3 "\${photon}/photon.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/photon
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    photon <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "photon <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/protosint b/UMBRELLA/Tools/protosint
--- a/UMBRELLA/Tools/protosint
+++ b/UMBRELLA/Tools/protosint
@@ -1,10 +1,12 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+bin=("git" "python")
+
 if [ ! -x $PREFIX/bin/protosint ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for protosint...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for protosint ..."
+    update_system
     git clone https://github.com/pixelbubble/ProtOSINT $PREFIX/opt/ProtOSINT
     touch $PREFIX/bin/protosint
     cat <<- Confg > $PREFIX/bin/protosint
@@ -14,10 +16,10 @@ cd \${protosint}
 exec python3 "\${protosint}/protosint.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/protosint
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    protosint <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "protosint <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/pwnedornot b/UMBRELLA/Tools/pwnedornot
--- a/UMBRELLA/Tools/pwnedornot
+++ b/UMBRELLA/Tools/pwnedornot
@@ -1,15 +1,19 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+local bin=("git" "python3")
+
 if [ ! -x $PREFIX/bin/pwnedornot ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for pwnedornot...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install html2text
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for pwnedornot ... "
+    update_system
+    if ! python3 -m pip install html2text; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/thewhiteh4t/pwnedOrNot $PREFIX/opt/pwnedOrNot
-    cd $PREFIX/opt/pwnedOrNot
-    chmod 711 *.sh
-    bash install.sh
+    chmod 711 $PREFIX/opt/pwnedOrNot/*.sh
+    bash $PREFIX/opt/pwnedOrNot/install.sh
     touch $PREFIX/bin/pwnedornot
     cat <<- Confg > $PREFIX/bin/pwnedornot
 #!/bin/bash
@@ -18,10 +22,10 @@ cd \${pwnedornot}
 exec python3 "\${pwnedornot}/pwnedornot.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/pwnedornot
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    pwnedornot <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "pwnedornot <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/qrlink b/UMBRELLA/Tools/qrlink
--- a/UMBRELLA/Tools/qrlink
+++ b/UMBRELLA/Tools/qrlink
@@ -1,15 +1,23 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+local bin=("git" "python")
+
 if [ ! -x $PREFIX/bin/qrlink ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for qrlink...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    pip install --upgrade pip &>/dev/null;
-    python3 -m pip install Pillow
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for qrlink ..."
+    update_system
+    if ! python3 -m pip install Pillow; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/Darkmux/qrlink $PREFIX/opt/qrlink
     cd $PREFIX/opt/qrlink
-    chmod 777 *.sh
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    chmod 777 $PREFIX/opt/qrlink/*.sh
+    if ! python3 -m pip install -r $PREFIX/opt/qrlink/requirements.txt &>/dev/null;then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/qrlink
     cat <<- Confg $PREFIX/bin/qrlink
 #!/bin/bash
@@ -18,10 +26,10 @@ cd \${qrlink}
 exec bash "\${qrlink}/qrlink.sh" "\$@"
 Confg
     chmod 711 $PREFIX/bin/qrlink
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    qrlink <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "qrlink <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/recon-ng b/UMBRELLA/Tools/recon-ng
--- a/UMBRELLA/Tools/recon-ng
+++ b/UMBRELLA/Tools/recon-ng
@@ -1,14 +1,19 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+local bin=("git" "python3")
+
 if [ ! -x $PREFIX/bin/recon-ng ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for recon-ng...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for recon-ng ... "
+    update_system
     git clone https://github.com/lanmaster53/recon-ng $PREFIX/opt/recon-ng
     cd $PREFIX/opt/recon-ng
-    chmod 711 recon-ng
-    python3 -m pip install -r REQUIREMENTS
+    chmod 711 $PREFIX/opt/recon-ng/recon-ng
+    if !python3 -m pip install -r $PREFIX/opt/recon-ng/REQUIREMENTS; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/recon-ng
     cat <<- Confg > $PREFIX/bin/recon-ng
 #!/bin/bash
@@ -17,10 +22,10 @@ cd \${reconng}
 exec python3 "\${reconng}/recon-ng" "\$@"
 Confg
     chmod 711 $PREFIX/bin/recon-ng
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    recon-ng\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "recon-gn <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/recondog b/UMBRELLA/Tools/recondog
--- a/UMBRELLA/Tools/recondog
+++ b/UMBRELLA/Tools/recondog
@@ -1,13 +1,19 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+bin=("git" "python3")
+
 if [ ! -x $PREFIX/bin/recondog ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for recondog...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for recondog ... "
+    update_system
     git clone https://github.com/s0md3v/ReconDog $PREFIX/opt/ReconDog
     cd $PREFIX/opt/ReconDog
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r $PREFIX/opt/ReconDog/requirements.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/recondog
     cat <<- Confg > $PREFIX/bin/recondog
 #!/bin/bash
@@ -16,10 +22,10 @@ cd \${recondog}
 exec python3 "\${recondog}/dog" "\$@"
 Confg
     chmod 711 $PREFIX/bin/recondog
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    recondog <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "recondog <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/redhawk b/UMBRELLA/Tools/redhawk
--- a/UMBRELLA/Tools/redhawk
+++ b/UMBRELLA/Tools/redhawk
@@ -1,9 +1,12 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+local bin=("git" "php")
+
 if [ ! -x $PREFIX/bin/redhawk ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for redhawk...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install php
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for redhawk ... "
+    update_system
     git clone https://github.com/Tuhinshubhra/RED_HAWK $PREFIX/opt/RED_HAWK
     touch $PREFIX/bin/redhawk
     cat <<- Confg > $PREFIX/bin/redhawk
@@ -13,10 +16,10 @@ cd \${redhawk}
 exec php "\${redhawk}/rhawk.php" "\$@"
 Confg
     chmod 711 $PREFIX/bin/redhawk
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    redhawk\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "redhawk <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/routersploit b/UMBRELLA/Tools/routersploit
--- a/UMBRELLA/Tools/routersploit
+++ b/UMBRELLA/Tools/routersploit
@@ -1,16 +1,24 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/routersploit ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for routersploit...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python make clang rust
-    python3 -m pip install --upgrade pip &>/dev/null;
-    yes|pkg install python-cryptography python-bcrypt
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python" "make" "clang" "rust" "python-cryptography" "python-bcrypt")
+  if [ ! -x $PREFIX/bin/routersploit ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for routersploit ... "
+
+    update_system
     git clone https://github.com/threat9/routersploit $PREFIX/opt/routersploit
-    cd $PREFIX/opt/routersploit
-    python3 -m pip install -r requirements.txt &>/dev/null
-    python3 -m pip install -r requirements-dev.txt &>/dev/null;
-    python3 setup.py install
+    if ! python3 -m pip install -r $PREFIX/opt/routersploit/requirements.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install -r $PREFIX/opt/routersploit/requirements-dev.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    python3 $PREFIX/opt/routersploit/setup.py install
     touch $PREFIX/bin/routersploit
     cat <<- Confg > $PREFIX/bin/routersploit
 #!/bin/bash
@@ -19,10 +27,13 @@ cd \${routersploit}
 exec python3 "\${routersploit}/rsf.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/routersploit
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "routersploit <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    routersploit <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/saycheese b/UMBRELLA/Tools/saycheese
--- a/UMBRELLA/Tools/saycheese
+++ b/UMBRELLA/Tools/saycheese
@@ -1,18 +1,25 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/saycheese ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for saycheese...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install wget php httrack openssh curl 
-    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/saycheese.zip -O $PREFIX/tmp/saycheese.zip
-    cd $PREFIX/tmp
-    unzip saycheese.zip
-    mv saycheese $PREFIX/opt
-    rm -rf saycheese.zip
-    cd $PREFIX/opt/saycheese
-    chmod 711 *.sh
-    ngrokserv
-    ln -s $PREFIX/bin/ngrok $PREFIX/opt/saycheese/ngrok
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "wget" "php" "httrack" "openssh" "curl" "unzip")
+
+  if [ ! -x $PREFIX/bin/saycheese ]; then
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for saycheese ... "
+
+    update_system
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/saycheese.zip -O $PREFIX/opt/saycheese.zip; then
+      unzip $PREFIX/opt/saycheese.zip
+      rm -r saycheese.zip
+      chmod 711 $PREFIX/opt/saycheese/*.sh
+      ngrokserv
+      ln -s $PREFIX/bin/ngrok $PREFIX/opt/saycheese/ngrok
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/saycheese
     cat <<- Confg > $PREFIX/bin/saycheese
 #!/bin/bash
@@ -21,10 +28,13 @@ cd \${saycheese}
 exec bash "\${saycheese}/saycheese.sh" "\$@"
 Confg
     chmod 711 $PREFIX/bin/saycheese
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "saycheese <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    saycheese <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/seeker b/UMBRELLA/Tools/seeker
--- a/UMBRELLA/Tools/seeker
+++ b/UMBRELLA/Tools/seeker
@@ -1,20 +1,25 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/seeker ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for seeker...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    yes|pkg install php
-    yes|pkg install curl
-    yes|pkg install wget
-    yes|pkg install openssh
-    pythob3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install packaging
-    python3 -m pip install requests
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python" "php" "curl" "wget" "openssh")
+
+  if [ ! -x $PREFIX/bin/seeker ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for seeker ... "
+    if ! python3 -m pip install packaging; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    if ! python3 -m pip install requests; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/thewhiteh4t/seeker $PREFIX/opt/seeker
-    cd $PREFIX/opt/seeker
-    chmod 711 install.sh
-    bash install.sh
+    chmod 711 $PREFIX/opt/seeker/install.sh
+    bash $PREFIX/opt/seeker/install.sh
     touch $PREFIX/bin/seeker
     cat <<- Confg > $PREFIX/bin/seeker
 #!/bin/bash
@@ -23,10 +28,13 @@ cd \${seeker}
 exec python3 "\${seeker}/seeker.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/seeker
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "seeker <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    seeker <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/sherlock b/UMBRELLA/Tools/sherlock
--- a/UMBRELLA/Tools/sherlock
+++ b/UMBRELLA/Tools/sherlock
@@ -1,28 +1,35 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/sherlock ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for sherlock...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    yes|pkg install python-numpy
-    yes|pkg install python-numpy-static
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python" "python-numpy" "python-numpy-static")
+
+  if [ ! -x $PREFIX/bin/sherlock ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for sherlock ... "
     MATHLIB="m" pip install pandas
     git clone https://github.com/sherlock-project/sherlock $PREFIX/opt/sherlock
-    cd $PREFIX/opt/sherlock
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r $PREFIX/opt/sherlock/requirements.txt &>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/sherlock
     cat <<- Confg > $PREFIX/bin/sherlock
 #!/bin/bash
 sherlock="/data/data/com.termux/files/usr/opt/sherlock/sherlock"
 cd \${sherlock}
-exec python3 "\${sherlock}/sherlock.py" "\$@"
+exec python3 "\${lock}/sherlock.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/sherlock
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    sherlock <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "sherlock <argv>"
+  else
+    log "$D Already Installed!"
 fi
+}
+
+main
diff --git a/UMBRELLA/Tools/sigit b/UMBRELLA/Tools/sigit
--- a/UMBRELLA/Tools/sigit
+++ b/UMBRELLA/Tools/sigit
@@ -1,19 +1,24 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/sigit ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for sigit...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install email_validator
-    git clone https://github.com/termuxhackers-id/SIGIT $PREFIX/opt/SIGIT
-    cd $PREFIX/opt/SIGIT
-    chmod 711 install.sh
-    bash install.sh
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    sigit <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+bin=("git" "python")
+
+if [ ! -x $PREFIX/bin/sigit ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for sigit ... "
+    if ! python3 -m pip install email_validator; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    git clone https://github.com/termuxhackers-id/SIGIT $PREFIX/opt/SIGIT
+    chmod 711 $PREFIX/opt/SIGIT/install.sh
+    bash $PREFIX/opt/SIGIT/install.sh
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "sigit <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/slowloris b/UMBRELLA/Tools/slowloris
--- a/UMBRELLA/Tools/slowloris
+++ b/UMBRELLA/Tools/slowloris
@@ -1,13 +1,15 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+bin=("git" "python3")
+
 if [ ! -x $PREFIX/bin/slowloris ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for slowloris...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for slowloris ... "
     git clone https://github.com/gkbrk/slowloris $PREFIX/opt/slowloris
-    cd $PREFIX/opt/slowloris
-    python3 setup.py install
+    python3 $PREFIX/opt/slowloris/setup.py install
     touch $PREFIX/bin/slowloris
     cat <<- Confg > $PREFIX/bin/slowloris
 #!/bin/bash
@@ -16,10 +18,10 @@ cd \${slowloris}
 exec python3 "\${slowloris}/slowloris.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/slowloris
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    slowloris <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "slowloris <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/speedtest b/UMBRELLA/Tools/speedtest
--- a/UMBRELLA/Tools/speedtest
+++ b/UMBRELLA/Tools/speedtest
@@ -1,15 +1,21 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/speedtest ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for speedtest...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install speedtest-cli
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    speedtest <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+bin=("git" "python3")
+
+if [ ! -x $PREFIX/bin/speedtest ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for speedtest ... "
+    if ! python3 -m pip install speedtest-cli; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "speedtest <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/sublist3r b/UMBRELLA/Tools/sublist3r
--- a/UMBRELLA/Tools/sublist3r
+++ b/UMBRELLA/Tools/sublist3r
@@ -1,13 +1,17 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+bin=("git" "python3")
 if [ ! -x $PREFIX/bin/sublist3r ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for sublist3r...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for sublist3r ... "
     git clone https://github.com/aboul3la/Sublist3r $PREFIX/opt/Sublist3r
-    cd $PREFIX/opt/Sublist3r
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r $PREFIX/opt/Sublist3r/requirements.txt 2>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/sublist3r
     cat <<- Confg > $PREFIX/bin/sublist3r
 #!/bin/bash
@@ -16,10 +20,10 @@ cd \${sublister}
 exec python3 "\${sublister}/sublist3r.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/sublist3r
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    sublist3r <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "sublist3r <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/tmate b/UMBRELLA/Tools/tmate
--- a/UMBRELLA/Tools/tmate
+++ b/UMBRELLA/Tools/tmate
@@ -1,13 +1,17 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/tmate ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for tmate...\e[0m\n"
-    yes|pkg update && yes|pkg upgrade
-    yes|pkg install openssh tmate
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
 
-    tmate <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+bin=("openssh" "tmate")
+
+  if [ ! -x $PREFIX/bin/tmate ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for tmate ... "
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "tmate <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/transwer b/UMBRELLA/Tools/transwer
--- a/UMBRELLA/Tools/transwer
+++ b/UMBRELLA/Tools/transwer
@@ -1,12 +1,15 @@
-#!/usr/bin/bash
-#
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+bin=("translate-shell" "bat" "git")
+
 if [ ! -x $PREFIX/bin/transwer ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for transwer...\e[0m\n"
-    yes|pkg update && yes|pkg upgrade
-    yes|pkg install translate-shell bat
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for transwer ... "
     git clone https://github.com/Darkmux/transwer $PREFIX/opt/transwer
-    cd $PREFIX/opt/transwer
-    chmod 711 *.sh
+    chmod 711 $PREFIX/opt/transwer/*.sh
     touch $PREFIX/bin/transwer
     cat <<- Confg > $PREFIX/bin/transwer
 #!/bin/bash
@@ -15,10 +18,10 @@ cd \${transwer}
 exec bash "\${transwer}/transwer.sh" "\$@"
 Confg
     chmod 711 $PREFIX/bin/transwer
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    transwer <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "transwer <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/vector b/UMBRELLA/Tools/vector
--- a/UMBRELLA/Tools/vector
+++ b/UMBRELLA/Tools/vector
@@ -1,15 +1,23 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/vector ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for vector...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
-    python3 -m pip install Pillow
-    yes|pkg install python-pillow
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python" "python-pillow")
+
+  if [ ! -x $PREFIX/bin/vector ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for vector ... "
+    if ! python3 -m pip install Pillow; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     git clone https://github.com/thesaderror/vector $PREFIX/opt/vector
-    cd $PREFIX/opt/vector
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r $PREFIX/opt/vector/requirements.txt 2>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/vector
     cat <<- Confg > $PREFIX/bin/vector
 #!/bin/bash
@@ -18,10 +26,13 @@ cd \${vector}
 exec python3 "\${vector}/vector.py" "\$@"
 Confg
     chmod 777 $PREFIX/bin/vector
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "vector <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    vector <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/weeman b/UMBRELLA/Tools/weeman
--- a/UMBRELLA/Tools/weeman
+++ b/UMBRELLA/Tools/weeman
@@ -1,13 +1,15 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/weeman ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for weeman...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python2
-    python2 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+bin=("python2" "tmate")
+
+  if [ ! -x $PREFIX/bin/weeman ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for weeman ... "
     git clone https://github.com/evait-security/weeman $PREFIX/opt/weeman
-    cd $PREFIX/opt/weeman
-    chmod 711 weeman.py
+    chmod 711 $PREFIX/opt/weeman/weeman.py
     touch $PREFIX/bin/weeman
     cat <<- Confg > $PREFIX/bin/weeman
 #!/bin/bash
@@ -16,10 +18,11 @@ cd \${weeman}
 exec python2 "\${weeman}/weeman.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/weeman
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    weeman\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "Installing dependencies for tmate ... "
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "weeman <argv>"
+  else
+    log "$D Already Installed!"
+  fi
diff --git a/UMBRELLA/Tools/wortex b/UMBRELLA/Tools/wortex
--- a/UMBRELLA/Tools/wortex
+++ b/UMBRELLA/Tools/wortex
@@ -1,17 +1,22 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/wortex ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for wortex...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    yes|pkg install wget
-    python3 -m pip install --upgrade pip &>/dev/null;
-    wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/wortex.zip -O $PREFIX/tmp/wortex.zip
-    cd $PREFIX/tmp
-    unzip wortex.zip
-    mv wortex $PREFIX/opt
-    rm -rf wortex.zip
-    cd $PREFIX/opt/wortex
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+main() {
+  local bin=("git" "python" "wget" "unzip")
+
+  if [ ! -x $PREFIX/bin/wortex ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for wortex ... "
+    if wget https://raw.githubusercontent.com/Darkmux/phoenix-packages/main/tools/wortex.zip -O $PREFIX/tmp/wortex.zip; then
+      unzip $PREFIX/tmp/wortex.zip
+      mv $PREFIX/tmp/wortex $PREFIX/opt
+      rm -r $PREFIX/tmp/wortex.zip
+    else
+      error "It could not be installed the package!."
+      exit 1
+    fi
     touch $PREFIX/bin/wortex
     cat <<- Confg > $PREFIX/bin/wortex
 #!/bin/bash
@@ -20,10 +25,13 @@ cd \${wortex}
 exec python3 "\${wortex}/wortex.py" "\$@"
 Confg
     chmod 711 $PREFIX/bin/wortex
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "wortex <argv>"
+  else
+    log "$D Already Installed!"
+  fi
+}
 
-    wortex\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+main
diff --git a/UMBRELLA/Tools/xsstrike b/UMBRELLA/Tools/xsstrike
--- a/UMBRELLA/Tools/xsstrike
+++ b/UMBRELLA/Tools/xsstrike
@@ -1,19 +1,24 @@
-#!/usr/bin/bash
-#
-if [ ! -x $PREFIX/bin/xsstrike ]; then
-    echo -en "\e[1;4;38;5;253mInstalling dependencies for xsstrike...\e[0m\n"
-    yes|pkg update && pkg upgrade
-    yes|pkg install python
-    python3 -m pip install --upgrade pip &>/dev/null;
+#!/usr/bin/env bash
+#Useful functions for customization of the Umbrella
+source "${HOME}/.UMBRELLA/UMBRELLA/functions" || { echo -en "\033[31mError:\033[33m File 'functions' is required but not exist!.\033[0m\n" ; exit 1; }
+
+bin=("python" "git")
+
+  if [ ! -x $PREFIX/bin/xsstrike ]; then
+    update_system
+    install_dependencies "${bin[@]}"
+    log "Installing dependencies for xsstrike ... "
     git clone https://github.com/s0md3v/XSStrike $PREFIX/opt/XSStrike
-    cd $PREFIX/opt/XSStrike
-    python3 -m pip install -r requirements.txt &>/dev/null;
+    if ! python3 -m pip install -r $PREFIX/opt/XSStrike/requirements.txt 2>/dev/null; then
+      error "It could not be installed the package!."
+      exit 1
+    fi
     ln -s $PREFIX/opt/XSStrike/xsstrike.py $PREFIX/bin/xsstrike
     chmod 711 $PREFIX/bin/xsstrike
-    printf "\e[1;38;5;253mDone!
-    Please Execute:
-
-    xsstrike <argv>\e[0m\n"
-else
-    echo -en "\e[1;4;38;5;253mAlready Installed!\e[0m\n";
-fi
+    log "$D Done!"
+    log "Please Execute:"
+    echo
+    log "xsstrike <argv>"
+  else
+    log "$D Already Installed!"
+  fi
